<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ExcelPdf</RootNamespace>

    <!-- NuGet properties -->
    <Version>1.0.0</Version>
    <Title>ExcelPdf</Title>
    <Authors>EnricoAlborghetti</Authors>
    <Description>A robust C# library for converting Excel files (XLSX) to PDF documents using NPOI and QuestPDF.</Description>
    <PackageProjectUrl>https://github.com/EnricoAlborghetti/ExcelPdf</PackageProjectUrl>
    <RepositoryUrl>https://github.com/EnricoAlborghetti/ExcelPdf.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.12.2" />
    <PackageReference Include="NPOI" Version="2.6.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
  </ItemGroup>

</Project>
